// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockTracker.BrandDetection.Data;

#nullable disable

namespace StockTracker.BrandDetection.Migrations
{
    [DbContext(typeof(BrandDetectionDbContext))]
    [Migration("20260805174237_AddStradivariusSignature")]
    partial class AddStradivariusSignature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockTracker.BrandDetection.Entities.BrandCodeSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RegexPattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("BrandCodeSignatures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BrandId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BrandName = "Bershka",
                            Confidence = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RegexPattern = "^\\d{11}$"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BrandId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            BrandName = "Zara",
                            Confidence = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RegexPattern = "^\\d{4}/\\d{3}/\\d{3}$"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BrandId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            BrandName = "Pull&Bear",
                            Confidence = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RegexPattern = "^\\d{8}/\\d{3}$"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BrandId = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            BrandName = "Mango",
                            Confidence = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RegexPattern = "^\\d{8}/\\d{2}$"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BrandId = new Guid("e5f6a7b8-c9d0-1234-eabc-345678901234"),
                            BrandName = "H&M",
                            Confidence = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RegexPattern = "^\\d{7}/\\d{3}$"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BrandId = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            BrandName = "Massimo Dutti",
                            Confidence = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RegexPattern = "^\\d{8}/\\d{3}$"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            BrandId = new Guid("a7b8c9d0-e1f2-3456-abcd-567890123456"),
                            BrandName = "Beymen",
                            Confidence = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RegexPattern = "^\\d{7}$"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            BrandId = new Guid("b8c9d0e1-f2a3-4567-bcde-678901234567"),
                            BrandName = "Stradivarius",
                            Confidence = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RegexPattern = "^\\d{8}$"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
