// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockTracker.StoreReference.Data;

#nullable disable

namespace StockTracker.StoreReference.Migrations
{
    [DbContext(typeof(StoreReferenceDbContext))]
    [Migration("20260728183233_UpdateBershkaStoresWithRealIds")]
    partial class UpdateBershkaStoresWithRealIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockTracker.StoreReference.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BrandSpecificStoreId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StoreName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "City", "District");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-0000-0000-0000-000000000001"),
                            BrandId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BrandName = "Bershka",
                            BrandSpecificStoreId = "16884",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Kadikoy",
                            IsActive = true,
                            StoreName = "City's Kozyatağı"
                        },
                        new
                        {
                            Id = new Guid("d1111111-0000-0000-0000-000000000002"),
                            BrandId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BrandName = "Bershka",
                            BrandSpecificStoreId = "8359",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sisli",
                            IsActive = true,
                            StoreName = "Cevahir AVM"
                        },
                        new
                        {
                            Id = new Guid("d1111111-0000-0000-0000-000000000003"),
                            BrandId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BrandName = "Bershka",
                            BrandSpecificStoreId = "6943",
                            City = "Ankara",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Cankaya",
                            IsActive = true,
                            StoreName = "Kentpark"
                        },
                        new
                        {
                            Id = new Guid("d1111111-0000-0000-0000-000000000004"),
                            BrandId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BrandName = "Bershka",
                            BrandSpecificStoreId = "8426",
                            City = "Izmir",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Bornova",
                            IsActive = true,
                            StoreName = "Forum Bornova"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
