// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockTracker.StoreReference.Data;

#nullable disable

namespace StockTracker.StoreReference.Migrations
{
    [DbContext(typeof(StoreReferenceDbContext))]
    [Migration("20260805132105_AddMassimoDuttiStores")]
    partial class AddMassimoDuttiStores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockTracker.StoreReference.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BrandSpecificStoreId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("StoreName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "City", "District");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-0000-0000-0000-000000000001"),
                            BrandId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BrandName = "Bershka",
                            BrandSpecificStoreId = "16884",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Kadikoy",
                            IsActive = true,
                            StoreName = "City's Kozyatağı"
                        },
                        new
                        {
                            Id = new Guid("d1111111-0000-0000-0000-000000000002"),
                            BrandId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BrandName = "Bershka",
                            BrandSpecificStoreId = "8359",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sisli",
                            IsActive = true,
                            StoreName = "Cevahir AVM"
                        },
                        new
                        {
                            Id = new Guid("d1111111-0000-0000-0000-000000000003"),
                            BrandId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BrandName = "Bershka",
                            BrandSpecificStoreId = "6943",
                            City = "Ankara",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Cankaya",
                            IsActive = true,
                            StoreName = "Kentpark"
                        },
                        new
                        {
                            Id = new Guid("d1111111-0000-0000-0000-000000000004"),
                            BrandId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BrandName = "Bershka",
                            BrandSpecificStoreId = "8426",
                            City = "Izmir",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Bornova",
                            IsActive = true,
                            StoreName = "Forum Bornova"
                        },
                        new
                        {
                            Id = new Guid("d2222222-0000-0000-0000-000000000001"),
                            BrandId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            BrandName = "Zara",
                            BrandSpecificStoreId = "3231",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Kadikoy",
                            IsActive = true,
                            StoreName = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("d2222222-0000-0000-0000-000000000002"),
                            BrandId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            BrandName = "Zara",
                            BrandSpecificStoreId = "12692",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sisli",
                            IsActive = true,
                            StoreName = "Cevahir AVM"
                        },
                        new
                        {
                            Id = new Guid("d2222222-0000-0000-0000-000000000003"),
                            BrandId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            BrandName = "Zara",
                            BrandSpecificStoreId = "251",
                            City = "Ankara",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Cankaya",
                            IsActive = true,
                            StoreName = "Kentpark"
                        },
                        new
                        {
                            Id = new Guid("d2222222-0000-0000-0000-000000000004"),
                            BrandId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            BrandName = "Zara",
                            BrandSpecificStoreId = "3643",
                            City = "Izmir",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Bornova",
                            IsActive = true,
                            StoreName = "Forum Bornova"
                        },
                        new
                        {
                            Id = new Guid("d3333333-0000-0000-0000-000000000001"),
                            BrandId = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            BrandName = "Mango",
                            BrandSpecificStoreId = "10389",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Kadikoy",
                            IsActive = true,
                            Latitude = 40.959937009724001,
                            Longitude = 29.080951331352001,
                            StoreName = "Bağdat Caddesi (Suadiye)"
                        },
                        new
                        {
                            Id = new Guid("d3333333-0000-0000-0000-000000000002"),
                            BrandId = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            BrandName = "Mango",
                            BrandSpecificStoreId = "10277",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sisli",
                            IsActive = true,
                            Latitude = 41.062784014649999,
                            Longitude = 28.992832831243,
                            StoreName = "Cevahir AVM"
                        },
                        new
                        {
                            Id = new Guid("d3333333-0000-0000-0000-000000000003"),
                            BrandId = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            BrandName = "Mango",
                            BrandSpecificStoreId = "10403",
                            City = "Ankara",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Cankaya",
                            IsActive = true,
                            Latitude = 39.909714541850001,
                            Longitude = 32.778216907751002,
                            StoreName = "CEPA AVM"
                        },
                        new
                        {
                            Id = new Guid("d3333333-0000-0000-0000-000000000004"),
                            BrandId = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            BrandName = "Mango",
                            BrandSpecificStoreId = "10711",
                            City = "Izmir",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Bornova",
                            IsActive = true,
                            Latitude = 38.450381582437998,
                            Longitude = 27.209401193083,
                            StoreName = "Forum Bornova"
                        },
                        new
                        {
                            Id = new Guid("d4444444-0000-0000-0000-000000000001"),
                            BrandId = new Guid("e5f6a7b8-c9d0-1234-eabc-345678901234"),
                            BrandName = "H&M",
                            BrandSpecificStoreId = "TR0030",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Kadikoy",
                            IsActive = true,
                            Latitude = 40.960302857690962,
                            Longitude = 29.080933150253259,
                            StoreName = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("d4444444-0000-0000-0000-000000000002"),
                            BrandId = new Guid("e5f6a7b8-c9d0-1234-eabc-345678901234"),
                            BrandName = "H&M",
                            BrandSpecificStoreId = "TR0028",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sisli",
                            IsActive = true,
                            Latitude = 41.077645374227643,
                            Longitude = 29.012837227783169,
                            StoreName = "Özdilek Park AVM"
                        },
                        new
                        {
                            Id = new Guid("d4444444-0000-0000-0000-000000000003"),
                            BrandId = new Guid("e5f6a7b8-c9d0-1234-eabc-345678901234"),
                            BrandName = "H&M",
                            BrandSpecificStoreId = "TR0007",
                            City = "Ankara",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Cankaya",
                            IsActive = true,
                            Latitude = 39.908593425610931,
                            Longitude = 32.778517871025088,
                            StoreName = "CEPA AVM"
                        },
                        new
                        {
                            Id = new Guid("d4444444-0000-0000-0000-000000000004"),
                            BrandId = new Guid("e5f6a7b8-c9d0-1234-eabc-345678901234"),
                            BrandName = "H&M",
                            BrandSpecificStoreId = "TR0075",
                            City = "Izmir",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Bornova",
                            IsActive = true,
                            Latitude = 38.338445,
                            Longitude = 27.135328999999999,
                            StoreName = "Optimum AVM"
                        },
                        new
                        {
                            Id = new Guid("d5555555-0000-0000-0000-000000000001"),
                            BrandId = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            BrandName = "Massimo Dutti",
                            BrandSpecificStoreId = "12013",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Kadikoy",
                            IsActive = true,
                            Latitude = 40.953105999999998,
                            Longitude = 29.121725000000001,
                            StoreName = "Hilltown AVM"
                        },
                        new
                        {
                            Id = new Guid("d5555555-0000-0000-0000-000000000002"),
                            BrandId = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            BrandName = "Massimo Dutti",
                            BrandSpecificStoreId = "4483",
                            City = "Istanbul",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Sisli",
                            IsActive = true,
                            Latitude = 41.063594999999999,
                            Longitude = 28.992114999999998,
                            StoreName = "Cevahir AVM"
                        },
                        new
                        {
                            Id = new Guid("d5555555-0000-0000-0000-000000000003"),
                            BrandId = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            BrandName = "Massimo Dutti",
                            BrandSpecificStoreId = "4009",
                            City = "Ankara",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Cankaya",
                            IsActive = true,
                            Latitude = 39.909011,
                            Longitude = 32.776290000000003,
                            StoreName = "Kentpark AVM"
                        },
                        new
                        {
                            Id = new Guid("d5555555-0000-0000-0000-000000000004"),
                            BrandId = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            BrandName = "Massimo Dutti",
                            BrandSpecificStoreId = "12840",
                            City = "Izmir",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Bornova",
                            IsActive = true,
                            Latitude = 38.478435099999999,
                            Longitude = 27.074343200000001,
                            StoreName = "Karşıyaka Rönesans AVM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
