// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockTracker.Subscription.Data;

#nullable disable

namespace StockTracker.Subscription.Migrations
{
    [DbContext(typeof(SubscriptionDbContext))]
    [Migration("20260804090600_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockTracker.Subscription.Entities.UserWatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WatchGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WatchGroupId");

                    b.HasIndex("UserId", "WatchGroupId")
                        .IsUnique();

                    b.ToTable("UserWatches");
                });

            modelBuilder.Entity("StockTracker.Subscription.Entities.WatchGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastKnownStatus")
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode", "Size", "StoreId");

                    b.ToTable("WatchGroups");
                });

            modelBuilder.Entity("StockTracker.Subscription.Entities.UserWatch", b =>
                {
                    b.HasOne("StockTracker.Subscription.Entities.WatchGroup", "WatchGroup")
                        .WithMany()
                        .HasForeignKey("WatchGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
