// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockTracker.Product.Data;

#nullable disable

namespace StockTracker.Product.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260807112703_AddMaviBrand")]
    partial class AddMaviBrand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockTracker.Product.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ScraperQueueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SearchEndpoint")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Bershka",
                            ScraperQueueName = "bershka",
                            SearchEndpoint = "https://www.bershka.com/tr/search"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Zara",
                            ScraperQueueName = "zara",
                            SearchEndpoint = "https://www.zara.com/tr/search"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Pull&Bear",
                            ScraperQueueName = "pullbear",
                            SearchEndpoint = "https://www.pullandbear.com/tr/search"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Mango",
                            ScraperQueueName = "mango",
                            SearchEndpoint = "https://shop.mango.com/tr/search"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-eabc-345678901234"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "H&M",
                            ScraperQueueName = "hm",
                            SearchEndpoint = "https://www2.hm.com/tr_tr/search-results.html"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Massimo Dutti",
                            ScraperQueueName = "massimodutti",
                            SearchEndpoint = "https://www.massimodutti.com/tr/search"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-abcd-567890123456"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Beymen",
                            ScraperQueueName = "beymen",
                            SearchEndpoint = "https://www.beymen.com/tr/arama"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4567-bcde-678901234567"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Stradivarius",
                            ScraperQueueName = "stradivarius",
                            SearchEndpoint = "https://www.stradivarius.com/tr/search"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-5678-cdef-789012345678"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Oysho",
                            ScraperQueueName = "oysho",
                            SearchEndpoint = "https://www.oysho.com/tr/search"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-6789-defa-890123456789"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Mavi",
                            ScraperQueueName = "mavi",
                            SearchEndpoint = "https://www.mavi.com/arama"
                        });
                });

            modelBuilder.Entity("StockTracker.Product.Entities.ProductBrandMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResolvedVia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("ProductUrl");

                    b.ToTable("ProductBrandMaps");
                });

            modelBuilder.Entity("StockTracker.Product.Entities.ProductBrandMap", b =>
                {
                    b.HasOne("StockTracker.Product.Entities.Brand", "Brand")
                        .WithMany("ProductBrandMaps")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("StockTracker.Product.Entities.Brand", b =>
                {
                    b.Navigation("ProductBrandMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
